#!/usr/bin/env python
import sys
import git_pre_commit_hook
import subprocess
import os


if __name__ == '__main__':
    cmd = ["git-pylint-commit-hook", "--limit", "8", "--always-show-violations"]
    p = subprocess.Popen(cmd)
    p.communicate()
    sys.exit(p.returncode)
